# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "firebase/hosting/package.json" }}
            - v1-dependencies-{{ checksum "firebase/functions/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          working_directory: firebase/hosting
          command: |
            yarn install
      - run:
          working_directory: firebase/functions
          command: |
            yarn install

      - save_cache:
          paths:
            - firebase/hosting/node_modules
          key: v1-dependencies-{{ checksum "firebase/hosting/package.json" }}
      - save_cache:
          paths:
            - firebase/functions/node_modules
          key: v1-dependencies-{{ checksum "firebase/functions/package.json" }}

      - run:
          working_directory: firebase/hosting
          command: |
            yarn run generate

      - run:
          working_directory: firebase
          command: |
            ./hosting/node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project=$FIREBASE_PROJECT_ID
